version: "3"

services:
  squid-proxy:
    build: .
    ports:
      - "8000-8900:3128"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
    environment:
      - SQUID_USER=proxy101
      - SQUID_PASS=BqFK_&zRFX!7uVFDb
      - CACHE_BACKEND=memcached
      - CACHE_HOST=memcached-server
      - CACHE_PORT=11211
    restart: always
    depends_on:
      - memcached-server
  memcached-server:
    image: memcached:latest
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
    ports:
      - "11211:11211"
    environment:
      - MEMCACHED_MAX_MEMORY=64
    restart: always
