version: '3'
services:
  mysql:
    image: mysql:latest
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: squid_root_password
      MYSQL_DATABASE: squid_db
      MYSQL_USER: squid_user
      MYSQL_PASSWORD: squid_password
  squid:
    build: .
    deploy:
      replicas: 1
    ports:
      - "8000-8900:3128"
    links:
       - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: squid_user
      MYSQL_PASSWORD: squid_password
      MYSQL_DATABASE: squid_db
    volumes:
      - cache1:/var/spool/squid/cache1
      - cache2:/var/spool/squid/cache2
      - cache3:/var/spool/squid/cache3
      - squidlogs:/var/log/squid
