version: '3.9'

services:
  mysql:
    image: mysql:latest
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: "6g"
        reservations:
          cpus: '4'
          memory: "4g"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: squid_root_password
      MYSQL_DATABASE: squid_db
      MYSQL_USER: squid_user
      MYSQL_PASSWORD: squid_password
  squid:
    build: .
    dns:
      - 8.8.8.8
      - 1.1.1.1
    network_mode: "host"
    extra_hosts:
      - "138.199.41.117:host-gateway"
      - "138.199.41.118:host-gateway"
      - "138.199.41.120:host-gateway"
      - "138.199.41.121:host-gateway"
      - "138.199.41.122:host-gateway"
    deploy:
      replicas: 100
      resources:
        limits:
          cpus: '4'
          memory: "4g"
        reservations:
          cpus: '2'
          memory: "2g"
    ports:
      - "8800-8900:3128"
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: squid_user
      MYSQL_PASSWORD: squid_password
      MYSQL_DATABASE: squid_db
    command: ["sh", "-c", "sleep 60 && echo 'Second container started'"]

