version: '3'
services:
  mysql:
    image: mysql:latest
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: squid_root_password
      MYSQL_DATABASE: squid_db
      MYSQL_USER: squid_user
      MYSQL_PASSWORD: squid_password
  squid:
    build: .
    deploy:
      replicas: 100
    ports:
      - "8800-8900:3128"
    links:
       - mysql
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: squid_user
      MYSQL_PASSWORD: squid_password
      MYSQL_DATABASE: squid_db
    command: ["sh", "-c", "sleep 60 && echo 'Second container started'"]
    networks:
      squid_IP1:
        ipv4_address: 138.199.41.117
        driver: bridge
      squid_IP2:
        ipv4_address: 138.199.41.118
        driver: bridge
      squid_IP3:
        ipv4_address: 138.199.41.120
        driver: bridge
      squid_IP4:
        ipv4_address: 138.199.41.121
        driver: bridge
      squid_IP5:
        ipv4_address: 138.199.41.122
        driver: bridge

