version: '3.9'
services:
  mysql:
    image: mysql:latest
    networks:
      - proxy_network
    dns:
      - 8.8.8.8
      - 1.1.1.1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: squid_root_password
      MYSQL_DATABASE: squid_db
      MYSQL_USER: squid_user
      MYSQL_PASSWORD: squid_password
  squid:
    build: .
    networks:
      - proxy_network
    dns:
      - 8.8.8.8
      - 1.1.1.1
    deploy:
      replicas: 100
    ports:
      - "8800-8900:3128"
    links:
       - mysql
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: squid_user
      MYSQL_PASSWORD: squid_password
      MYSQL_DATABASE: squid_db
    command: ["sh", "-c", "sleep 60 && echo 'Second container started'"]

