version: '3'
services:
  squid:
    build: .
    ports:
      - "8000-8900:3128"
    links:
       - mysql
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: squid_user
      MYSQL_PASSWORD: squid_password
      MYSQL_DATABASE: squid_db
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    links:
       - squid
    environment:
      MYSQL_ROOT_PASSWORD: squid_root_password
      MYSQL_DATABASE: squid_db
      MYSQL_USER: squid_user
      MYSQL_PASSWORD: squid_password
