version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: squid_root_password
      MYSQL_DATABASE: squid_db
      MYSQL_USER: squid_user
      MYSQL_PASSWORD: squid_password
  squid:
    build: .
    ports:
      - "8000-8900:3128"
    links:
       - mysql
    depends_on:
      - mysql:
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "mysql"]
        interval: 10s
        timeout: 5s
        retries: 3
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: squid_user
      MYSQL_PASSWORD: squid_password
      MYSQL_DATABASE: squid_db
