version: '3'
services:
  mysql:
    image: mysql:latest
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: squid_root_password
      MYSQL_DATABASE: squid_db
      MYSQL_USER: squid_user
      MYSQL_PASSWORD: squid_password
  squid:
    build: .
    deploy:
      replicas: 100
    ports:
      - "8800-8900:3128"
    links:
       - mysql
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure
    networks:
      proxysquid_default:
        dns:
          - 8.8.8.8
          - 1.1.1.1
          - 8.8.4.4
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: squid_user
      MYSQL_PASSWORD: squid_password
      MYSQL_DATABASE: squid_db
      PUBLIC_IP: 138.199.41.$((117 + RANDOM % 5))
    command: ["sh", "-c", "sleep 60 && echo 'Second container started'"]

