version: "3"

services:
  squid-proxy:
    build: .
    ports:
      - "8000-8900:8000-8900"
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "2"
          memory: 2G
    environment:
      - CACHE_BACKEND=memcached
      - CACHE_HOST=memcached-server
      - CACHE_PORT=11211
    restart: always
    depends_on:
      - memcached
  memcached:
    image: memcached:latest
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "2"
          memory: 2G
    ports:
      - "11211:11211"
    environment:
      - MEMCACHED_MAX_MEMORY=64
    restart: always
